# ?? ?? ? response ? message ????
server:
  port: 5000
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME:localhost}:${RDS_PORT:3300}/${RDS_DB_NAME:bbs}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${RDS_USERNAME:bbs}
    password: ${RDS_PASSWORD:jong9612!}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB


file:
  dir: C:\Users\User\Desktop\imagefolder\


#logging:
#  level:
#    org:
#      apache:
#        coyote:
#          http11: debug
